### ISSUE TITLE
document units

### ISSUE THREAD

**Issue by nickolasclarke** [geoinsights/ChinaAQIData#1]
It is unclear what units the different pollutants are reported in. While I can infer the units by looking at other sources, it would be good to add those explicitly to the converted XML or at least to the JSON. Can you help confirm the units being reported?

**Comment by GeoInsights** [comment]
The source data stream does not contain the units for each pollutant. However, through verifying some cases from the source web site(CNEMC http://www.cnemc.cn/),  you can infer the units: 
For pollutants PM2.5, PM10, SO2,NO2, O3, the unit is  *μg/m^3*.
For CO, the unit is  *mg/m^3*. @nickolasclarke

**Comment by nickolasclarke** [comment]
@geoinsights yes, however, I do think it would be valuable to include this information as part of the project no? I can provide a PR if needed. I'll be including it on my fork regardless.

**Comment by GeoInsights** [comment]
@nickolasclarke You are right, the unit information is valuable for the project.  I will appreciate it if you could provide a pull request. Thanks a lot for reminding me. 🙂

**Comment by nickolasclarke** [comment]
@geoinsights sounds great.

**Comment by jflasher** [comment]
@geoinsights thanks for this work! Where do you think the right place to add the units would be? Because it's not included in the original stream, I'm not sure it should be added to the`data.xml`. I think maybe it should just be added in `xml2json.py`?
